config/routes.rb
Rails.application.routes.draw do
  
  get '/profile/:id', to: 'users#profile', as: :users
  
  resources :posts do
	  member do
	    put "like", to: "posts#like"
	  end
end

  
  
  root 'users#home'

 
  devise_for :users
  resources :groups

  
end

app/models/following.rb
class Following < ActiveRecord::Base
	belongs_to :user
	belongs_to :group
end

app/models/group.rb
class Group < ActiveRecord::Base

	# a_user.groups << some_group
	has_and_belongs_to_many :users, dependent: :destroy
	has_many :followings
	has_many :subscribers, through: :followings, source: :user
end

app/models/like.rb
class Like < ActiveRecord::Base
	belongs_to :posts
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
  	validates :body, presence: true, length: { maximum: 160 }
  	has_attached_file :image, :styles => { :large => "600x600>", :medium => "300x300>", :thumb => "100x100>" } 
  	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  	acts_as_votable
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	has_and_belongs_to_many :groups
	has_many :followings
	has_many :subscriptions, through: :followings, source: :group
	has_many :posts, dependent: :destroy
  	has_attached_file :avatar, :styles => { :large => "600x600>", :medium => "300x300>", :thumb => "100x100>" } 
  	validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception

  protected

  def after_sign_up_path_for(resource)
	users_path(current_user.id)
  end

  def after_sign_in_path_for(resource)
  users_path(current_user.id)
  end

  def configure_permitted_parameters
   devise_parameter_sanitizer.for(:sign_up) << :name 
   devise_parameter_sanitizer.for(:sign_up) << :title 
   devise_parameter_sanitizer.for(:sign_up) << :avatar
   devise_parameter_sanitizer.for(:sign_up) << :description
   devise_parameter_sanitizer.for(:account_update) << :name
   devise_parameter_sanitizer.for(:account_update) << :title
   devise_parameter_sanitizer.for(:account_update) << :avatar
   devise_parameter_sanitizer.for(:account_update) << :description
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  
  def index
    @groups = Group.all
    @users = User.all
  end

  def create
  @group = Group.new(params.require(:group).permit(:name, :description))
  @group.users << current_user
    if @group.save
      
      redirect_to groups_path , notice: "New group created!"
    else

  end
end

  def new
    @group = Group.new
  end

  def show
    @users = User.all
    @group = Group.find(params[:id])
    
  end

  def update
    @group = Group.find(params[:id])
    @group.users << @current_user
  end

  def edit
  end
end

app/controllers/groups_users_controller.rb
class GroupsUsersController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  

  def index
    @posts = Post.all
    @users = User.all
  end

  def new
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
  end

  def like
    @post = Post.find(params[:id])
    @post.liked_by current_user
    redirect_to users_path(@post.user), notice: "You just liked it!"
  end


  def create
    @post = Post.new(post_params)


    if @post.save
      redirect_to root_path, notice: "New post created!"
    else
      flash[:notice] = @post.errors.full_messages
      render :new
    end

    
  end

  def update
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    respond_to do |format|
      format.html { redirect_to root_path, alert: "Post deleted." }
      format.js #{ render nothing: true }
  end
end
private

def post_params
  params.require(:post).permit(:title, :body, :image).merge(user: current_user)
end



def set_post
  @post = Post.find(params[:id])
end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!, only: [:edit, :update, :destroy, :close, :password]



  def profile
    
    @user = current_user
    @theuser = User.find(params[:id])
    @post = Post.new
    @posts = @theuser.posts.all
  end

  def close
  end

  def password
  	@user = current_user
  end

  def new
  	@user = User.new
  end

  def edit
  	@user = current_user
  end

  def show
    @user = User.find_by_username(params[:username])
    @post = @user.posts.all

    
  end

  def home
  end


  

  
  end

 

	

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/group_helper.rb
module GroupHelper
end

app/helpers/groups_users_helper.rb
module GroupsUsersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/groups/edit.html.erb
<h1>Group#edit</h1>
<p>Find me in app/views/group/edit.html.erb</p>

app/views/groups/index.html.erb
		<h3><%= current_user.email %> </h3>
	
<div class="box">
<% @groups.each do |group| %>

	<div class="boxes">
	<%= link_to group.name, group_path(group) %>
	<% if current_user.groups.include?(group) %>
		<%= link_to 'leave', root_path %>
	<% elsif current_user.groups.empty? %>
		<%= link_to 'join', root_path %>
	<% end %> 

	<% group.users.each do |user| %>
		<%= user.email %>
	<% end %>
		
	</div>	
	
<% end %>
</div>

app/views/groups/new.html.erb
<!-- form for creating a group -->


<div class="group-form">

<%= form_for @group do |f| %>
	<div>
		<%= f.text_field :name, :placeholder => "groupname" %>
	</div>
	<br>	
	<div>
		<%= f.submit %>
	</div>
<% end %>
</div>

app/views/groups/show.html.erb
<div class= "blog-title">
	<h1><%= @group.name %></h1>
</div>

<div class= "box">
 
	<% @group.users.each do |user| %>

	
	<div class= "boxes">
		<h1><%= user.title %></h1>
		<p>By</p>
		<h3><%= user.name %></h3> 
 		<%= link_to 'Enter', users_path(user.id), class:'link' %>
	</div>

		<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TheWave</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
	<%= render 'shared/header' %>
	

<%= yield %>


</body>
</html>

app/views/posts/_post.html.erb
<% if current_user == @theuser %>	
	
	<div class= "buttons">
		<%= link_to 'post', new_post_path %> 
	</div>
<% end %>
	
<div class= "profile-header">

	<h1><%= @theuser.title %></h1>
</div>		
	<div class= "profile">
		<div class= "profile-image">
		<%= image_tag @theuser.avatar.url(:thumb) %>
		</div>
			<h2><%= @theuser.name %></h2>
					<% if @user.groups.any? %>
						<h5>@<%= @theuser.groups.first.name if @theuser.groups.any? %></h5>  
					<% end %>
<br>
				<div class= "bio">
					<h4><%= @theuser.description %></h4>
				</div>

		
		<div id="social-bar"> 
			<ul>
				<li><div id="facebook" class="icon"></div></li>
				<li><div id="twitter" class="icon"></div></li>
				<li><div id="instagram" class="icon"></div></li>
			</ul>
		</div>
	</div>


	
<% if @posts %> 
	<% @posts.reverse.each do |post| %>
		
		<div class= "posts">
			
			<div class="like">
				<p><%= link_to 'Like', like_post_path(post.id), method: :put %></p>
			</div>
			<div class= "mainbio">
				<h3><%= post.title %><h3>
				<p><%= post.body %><p>
				<%= image_tag post.image.url(:medium) %></div>
				<div class= "votes">
					<%= post.votes_for.size %>
				</div>
	   	
		   	<div class="delete">
				<% if current_user == post.user %>
					<%= link_to 'delete', post, method: :delete, data: {remote: true, removable: true} %> 
				<% end %>
			</div>
	
		</div>
	
	<% end %>
<% end %>
			



				
			
	
	
	

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/edit.html.erb
<h1>Posts#edit</h1>
<p>Find me in app/views/posts/edit.html.erb</p>

app/views/posts/index.html.erb
<h1>Posts#index</h1>
<p>Find me in app/views/posts/index.html.erb</p>

app/views/posts/new.html.erb
<br>
<br>
<%= flash[:notice] if flash[:notice] %>
<%= form_for @post, url: posts_path, :html => { :multipart => true } do |f| %>


		<div class= "text">

			
			<%= f.text_field :title, placeholder: "title"%>
			<br>
			<br>
			
			<%= f.text_area :body, placeholder: "Write a post" %>
<br>
<br>
			
			<%= f.file_field :image %>

			
<br>
<br>
			<%= f.submit "Post" %>
			</div>
		<% end %>

app/views/posts/show.html.erb
<div class= "posts">
			
	<div class="like">
		<p><%= link_to 'Like', like_post_path(@post.id), method: :put %></p>
	</div>
		<h3><%= @post.title %><h3>
		<p><%= @post.body %><p>
		<%= image_tag @post.image.url(:medium) %>

		<p> <%= @post.votes_for.size %>

	
   	<div class="delete">
		<% if current_user == @post.user %>
			<%= link_to 'delete', @post, method: :delete, data: {remote: true, removable: true} %> 
		<% end %>
	</div>
	
</div>

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>

app/views/shared/_header.html.erb
 
<header class="navigation" role="banner">
  <div class="navigation-wrapper">

    <a href="javascript:void(0)" class="logo">
      
        <nav role="navigation">
      <ul id="js-navigation-menu" class="navigation-menu show">

      <% if user_signed_in? and current_user.groups.any? %>
        <li class="nav-link"><%= link_to current_user.groups.first.name, group_path(current_user.groups.first) %></li>
     <% elsif user_signed_in? %>
        <li class="nav-link"><%= link_to 'join a group', groups_path %></li>
     <% end %>

       

          <% if user_signed_in? %>

    <li class="nav-link more"><a href="javascript:void(0)">Me</a>
      <ul class="submenu">
        <li class="nav-link">

          <%= link_to 'profile', users_path(current_user.id) %></li>
              <li><%= link_to 'edit', edit_user_registration_path %></li>
                  <li class="more"><a href="javascript:void(0)">Groups</a>
                    <ul class="submenu">
                      <li><%= link_to 'Create', new_group_path %></li>
                      <li><%= link_to 'Join', groups_path %></li>
                    </ul>
                  </li>
      </ul>
    </li>



     

      <li class="nav-link">
      <%= link_to 'logout', destroy_user_session_path, class: :button, method: :delete %> </li>






    <% else %>

      <li class="nav-link">
      <%= link_to 'Browse', new_user_registration_path, class: :button %></li>
      
        
       
    <% end %>
        
      </ul>
    </nav>
    <div class="navigation-tools">
      <div class="search-bar">
        <form role="search">
          <input type="search" placeholder="Enter Search" />
          <button type="submit">
           
          </button>
        </form>
      </div>
    </div>
  </div>
</header>



    

app/views/users/home.html.erb
<!-- first page you see when yo go to this website
 -->
<div class= "wave">
 
<h1>Welcome to the Wave!</h1>
	<p>sign in or create an account</p>



      <%= link_to 'sign up', new_user_registration_path, class: :button %>
      
       
      <%= link_to 'log in', new_user_session_path, class: :button %> 

  </div>

app/views/users/profile.html.erb
	

<%= render "posts/post" %>



		